export const loginConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
};
export const logoutConstants = {
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
};

export const registerContants = {
  ADMIN_REGISTER_REQUEST: "ADMIN_REGISTER_REQUEST",
  ADMIN_REGISTER_SUCCESS: "ADMIN_REGISTER_SUCCESS",
  ADMIN_REGISTER_FAILURE: "ADMIN_REGISTER_FAILURE",
};

export const initialDataConstants = {
  GET_ALL_INITIAL_DATA_REQUEST: "GET_ALL_INITIAL_DATA_REQUEST",
  GET_ALL_INITIAL_DATA_SUCCESS: "GET_ALL_INITIAL_DATA_SUCCESS",
  GET_ALL_INITIAL_DATA_FAILURE: "GET_ALL_INITIAL_DATA_FAILURE",
};

export const manageAdminConstants = {
  GET_ALL_ADMIN_REQUEST: "GET_ALL_ADMIN_REQUEST",
  GET_ALL_ADMIN_SUCCESS: "GET_ALL_ADMIN_SUCCESS",
  GET_ALL_ADMIN_FAILURE: "GET_ALL_ADMIN_FAILURE",

  DELETE_ONE_ADMIN_REQUEST: "DELETE_ONE_ADMIN_REQUEST",
  DELETE_ONE_ADMIN_SUCCESS: "DELETE_ONE_ADMIN_SUCCESS",
  DELETE_ONE_ADMIN_FAILURE: "DELETE_ONE_ADMIN_FAILURE",
};

export const settingConstants = {

  UPDATE_INFORMATION_SUCCESS: "UPDATE_INFORMATION_SUCCESS",

  CHANGE_INFORMATION_REQUEST: "CHANGE_INFORMATION_REQUEST",
  CHANGE_INFORMATION_SUCCESS: "CHANGE_INFORMATION_SUCCESS",
  CHANGE_INFORMATION_FAILURE: "CHANGE_INFORMATION_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",
};
